"""empty message

Revision ID: 0e4c4d66f77e
Revises: 0fc411d473d5
Create Date: 2026-04-04 15:18:19.003678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4c4d66f77e'
down_revision = '0fc411d473d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('website_url', sa.String(length=250), nullable=False),
    sa.Column('logo_img', sa.String(length=250), nullable=False),
    sa.Column('banner_img', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
