"""empty message

Revision ID: 37566fb1f1de
Revises: 0671e396e2dc
Create Date: 2026-04-11 01:37:12.699367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37566fb1f1de'
down_revision = '0671e396e2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('trailer_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('cover_img',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('cover_img',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('trailer_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
