"""empty message

Revision ID: 3cbaa77c2766
Revises: b2d8c4a9e3d8
Create Date: 2026-04-06 02:29:02.174186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbaa77c2766'
down_revision = 'b2d8c4a9e3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_console', schema=None) as batch_op:
        batch_op.create_unique_constraint('_game_console_uc', ['game_id', 'console_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_console', schema=None) as batch_op:
        batch_op.drop_constraint('_game_console_uc', type_='unique')

    # ### end Alembic commands ###
