"""empty message

Revision ID: df2a374c4810
Revises: 2e91361232b4
Create Date: 2026-04-05 18:49:03.769302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2a374c4810'
down_revision = '2e91361232b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('trailer_url',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('game_trailer_url_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('game_trailer_url_key'), ['trailer_url'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('trailer_url',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
