"""empty message

Revision ID: e52fb1e6d261
Revises: 841d5893390d
Create Date: 2026-04-11 22:56:08.284368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52fb1e6d261'
down_revision = '841d5893390d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_post', schema=None) as batch_op:
        batch_op.drop_column('shares')

    # ### end Alembic commands ###
